name: Preview to Github Pages
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  pull-requests: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Install pnpm â¤ï¸ï¸
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }} â¤ï¸ï¸
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install and Build Frontend ğŸ”§
        run: |
          pnpm install
          pnpm build
        env:
          VITE_BASE_URL: /project-x/preview/${{ github.event.number }}

      - name: Github Preview Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
          COMMIT-MESSAGE: 'Deploy preview for PR #${{ github.event.number }} ğŸš€'
          TARGET-FOLDER: preview/${{ github.event.number }}
          GIT-CONFIG-NAME: github-actions[bot]
          GIT-CONFIG-EMAIL: github-actions[bot]@users.noreply.github.com

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: test-env
          message: |
            See the preview at https://victorwinberg.github.io/project-x/preview/${{ github.event.number }}
